### PR TITLE
Linting the codebase to be PEP 8 compliant with black for readibility 

### PR DESCRIPTION
**Pull request by TamaraAtanasoska**
This PR is making the codebase PEP 8 compliant, by linting with the [black linter](https://github.com/psf/black).
Black has found that 76 files need to be changed. 

Why I am proposing this change:
- I spent a lot of time reading code from the codebase in the last few weeks and I have done this for myself to make it more readable. It keeps the long lines and the docstrings tidy so they are more readable to someone new coming. 
- Keeping to PEP 8 standards is good for maintainability and it sets a standard for external people who would like to contribute as they have a guideline to follow.

### CODE REVIEW

**Comment by susuhahnml** [comment]
Hi @TamaraAtanasoska, thank you again for the contribution. I understand this is something you ran locally to format all files. Did you add this black linter as a dependency? I would like to apply this linter directly in the dev branch to avoid a complex merge.

**Comment by TamaraAtanasoska** [comment]
> Hi @TamaraAtanasoska, thank you again for the contribution. I understand this is something you ran locally to format all files. Did you add this black linter as a dependency? I would like to apply this linter directly in the dev branch to avoid a complex merge.

Hi! Thanks again for being interested in merging this. Yes, I ran the linter locally and I didn't include it anywhere since I didn't know to what extent you would be interested in using it. My favourite option is to include the linter in a [GitHub action like this](https://black.readthedocs.io/en/stable/integrations/github_actions.html) so anyone new contributing can write code as they want, but when it will be merged it will be formatted so the style is always compliant. If you agree to it, I am happy to add to this branch the `.github/workflows/black.yml` as described there in the documentation. For the code that is already there just running it once then would suffice as all future cases would be covered. What do you think?

**Comment by TamaraAtanasoska** [comment]
Hi @susuhahnml, any news on this? Can I do something?

**Comment by alexl4123** [comment]
Hi @TamaraAtanasoska ,

thank you for your contribution :)
It is planned to lint the code base and will be done soon. We plan to lint the development branch, therefore I will close this pull request.
See also issue #122

**Pull request closed without merging**
